"""add showroom_pages table

Revision ID: 8cd6c7e6a2d8
Revises: 
Create Date: 2026-03-15 19:54:29.082081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cd6c7e6a2d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showroom_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.String(length=100), nullable=False),
    sa.Column('page_token', sa.Text(), nullable=False),
    sa.Column('phone_id', sa.String(length=100), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('showroom_pages')
    # ### end Alembic commands ###
